"""add notifications table

Revision ID: 7083d795c5b1
Revises: 01d4da58d431
Create Date: 2020-02-03 20:46:43.139773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7083d795c5b1'
down_revision = '01d4da58d431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_messages_read_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_message_read_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_read_time', sa.DATETIME(), nullable=True))
        batch_op.drop_column('last_messages_read_time')

    # ### end Alembic commands ###
